name: sgxl
channels:
  - pytorch
  - nvidia
  # - conda-forge
dependencies:
  - python >= 3.8
  - pip
  - numpy==1.22.4
  - click>=8.0
  - pillow=9.2.0
  - scipy=1.7.1
  - pytorch=1.10.2
  - cudatoolkit=11.3.1
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib=3.4.2
  - imageio=2.9.0
  - dill=0.3.4
  - psutil=5.8.0
  - regex=2022.3.15
  - pip:
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - pyspng
    - ftfy==6.1.1
    - timm==0.4.12